export 'game/index.dart';
export 'home/indexd.dart';
export 'instruction/index.dart';
export 'main_page.dart';
export 'notice/index.dart';
export 'page_list.dart';
export 'splash/app_splash.dart';
export 'start/index.dart';
export 'text_scale_factor.dart';
